//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHangHoa_Sach
    {
        public int MaHangHoa { get; set; }
        public string TheLoai { get; set; }
        public string TacGia { get; set; }
        public string TomTatNoiDung { get; set; }
        public string NhaXuatBan { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
    }
}
