//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHangHoa_DienTu
    {
        public int MaHangHoa { get; set; }
        public string NhanHang { get; set; }
        public string MauSac { get; set; }
        public string MoTaSanPham { get; set; }
        public string CongSuat { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
    }
}
