//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatHang()
        {
            this.DonGiaoHangs = new HashSet<DonGiaoHang>();
            this.LichSuXuatKhoes = new HashSet<LichSuXuatKho>();
            this.ThongTinDatHangs = new HashSet<ThongTinDatHang>();
        }
    
        public int MaDon { get; set; }
        public int MaKhachHang { get; set; }
        public string DiaChi_KH { get; set; }
        public string SDT_KH { get; set; }
        public Nullable<System.DateTime> NgayLapDon { get; set; }
        public System.DateTime NgayGiaoHangDuKien { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public string TinhTrangDonHang { get; set; }
        public decimal TienShip { get; set; }
        public decimal TongTien { get; set; }
    
        public virtual SoDiaChi SoDiaChi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonGiaoHang> DonGiaoHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuXuatKho> LichSuXuatKhoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinDatHang> ThongTinDatHangs { get; set; }
    }
}
