//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kho()
        {
            this.LichSuNhapKhoes = new HashSet<LichSuNhapKho>();
            this.LichSuXuatKhoes = new HashSet<LichSuXuatKho>();
            this.ThongTinHangTons = new HashSet<ThongTinHangTon>();
        }
    
        public int MaKho { get; set; }
        public int MaNVQL { get; set; }
        public string TenKho { get; set; }
        public string DiaChiKho { get; set; }
    
        public virtual NhanVien_VanPhong NhanVien_VanPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuNhapKho> LichSuNhapKhoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuXuatKho> LichSuXuatKhoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinHangTon> ThongTinHangTons { get; set; }
    }
}
