//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuNhapKho
    {
        public System.DateTime NgayNhapKho { get; set; }
        public int MaHangHoa { get; set; }
        public int MaDonVi { get; set; }
        public int MaKho { get; set; }
        public int SoLuongNhapKho { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual NhaPhanPhoi NhaPhanPhoi { get; set; }
    }
}
