//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinDatHang
    {
        public int MaHangHoa { get; set; }
        public int MaDon { get; set; }
        public int SoLuongDat { get; set; }
    
        public virtual DonDatHang DonDatHang { get; set; }
        public virtual HangHoa HangHoa { get; set; }
    }
}
