//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public System.DateTime ThoigianFeedback { get; set; }
        public int MaHangHoa { get; set; }
        public string Noidung { get; set; }
        public int MaKhachHang { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
