//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HangHoa()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.LichSuNhapKhoes = new HashSet<LichSuNhapKho>();
            this.ThongTinDatHangs = new HashSet<ThongTinDatHang>();
            this.ThongTinHangTons = new HashSet<ThongTinHangTon>();
            this.NhaPhanPhois = new HashSet<NhaPhanPhoi>();
        }
    
        public int MaHangHoa { get; set; }
        public int MaLoaiHang { get; set; }
        public string TenHangHoa { get; set; }
        public decimal DonGia { get; set; }
    
        public virtual ChiTietHangHoa_DienTu ChiTietHangHoa_DienTu { get; set; }
        public virtual ChiTietHangHoa_Sach ChiTietHangHoa_Sach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual LoaiHang LoaiHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuNhapKho> LichSuNhapKhoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinDatHang> ThongTinDatHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinHangTon> ThongTinHangTons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhaPhanPhoi> NhaPhanPhois { get; set; }
    }
}
