//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shopping
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TIKIEntities : DbContext
    {
        public TIKIEntities()
            : base("name=TIKIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietHangHoa_DienTu> ChiTietHangHoa_DienTu { get; set; }
        public virtual DbSet<ChiTietHangHoa_Sach> ChiTietHangHoa_Sach { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<DonDatHang> DonDatHangs { get; set; }
        public virtual DbSet<DonGiaoHang> DonGiaoHangs { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<HangHoa> HangHoas { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<Kho> Khoes { get; set; }
        public virtual DbSet<LichSuNhapKho> LichSuNhapKhoes { get; set; }
        public virtual DbSet<LichSuXuatKho> LichSuXuatKhoes { get; set; }
        public virtual DbSet<LoaiHang> LoaiHangs { get; set; }
        public virtual DbSet<NhanVien_GiaoHang> NhanVien_GiaoHang { get; set; }
        public virtual DbSet<NhanVien_VanPhong> NhanVien_VanPhong { get; set; }
        public virtual DbSet<NhaPhanPhoi> NhaPhanPhois { get; set; }
        public virtual DbSet<SoDiaChi> SoDiaChis { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<ThongTinDatHang> ThongTinDatHangs { get; set; }
        public virtual DbSet<ThongTinHangTon> ThongTinHangTons { get; set; }
    }
}
