//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaPhanPhoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaPhanPhoi()
        {
            this.LichSuNhapKhoes = new HashSet<LichSuNhapKho>();
        }
    
        public int MaDonVi { get; set; }
        public string TenDonVi { get; set; }
        public string SDT_DV { get; set; }
        public string DiaChi_DV { get; set; }
        public string Email_DV { get; set; }
        public string Fax { get; set; }
        public string GiayPhepKinhDoanh { get; set; }
        public string TenDangNhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuNhapKho> LichSuNhapKhoes { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual HangHoa HangHoa { get; set; }
    }
}
